### ISSUE TITLE
ImportError: No module named config ?

### ISSUE THREAD

**Issue by varun-naharia** [eddwinn/redditAutobot#1]
I am unable to run the script. I am getting error

 ```
sudo python run.py 
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from app.regularbot import upvoteBot, commentbot, randomcomments
  File "/Users/varun/Documents/redditAutobot-master/app/__init__.py", line 4, in <module>
    from config import SQLALCHEMY_DATABASE_URI, SQLALCHEMY_DATABASE_URI_2
ImportError: No module named config
```

Please help how to fix this and run the code.

**Comment by eddwinn** [comment]
Will fix in the next few hours

**Comment by eddwinn** [comment]
Should be solved
